name: CI/CD Pipeline

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pip
            .mypy_cache
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt', '**/requirements-dev.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Install development dependencies
        run: pip install -r requirements-dev.txt

      - name: Run PEP8 linting and generate report
        run: |
          flake8 app --output-file=flake8report.txt

      - name: Run static analysis and generate report
        run: |
          mypy app --html-report mypy_report

      - name: Run pytest with parallel execution and coverage
        run: |
          pytest -n auto --cov=app --cov-report=xml:coverage.xml

      - name: Run security scanning
        run: |
          pip install bandit
          bandit -r app -o bandit_report.txt

      - name: Upload linting, static analysis, and security reports
        uses: actions/upload-artifact@v3
        with:
          name: code-quality-reports
          path: |
            flake8report.txt
            mypy_report/*
            bandit_report.txt

      - name: Upload test results and coverage report
        uses: actions/upload-artifact@v3
        with:
          name: test-and-coverage-results
          path: |
            report.xml
            coverage.xml